[project]
name = "de374-lot2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "earthkit>=0.13.2",
    "eccodes>=2.44.0",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
]
